

library(shiny)
ui <- fluidPage(
        titlePanel("Simulation"),
        sliderInput(inputId = 'N', 
                    label = 'Number of points', 
                    value = 3000, 
                    min = 100, 
                    max = 10000),
        sliderInput(inputId = 'Num_public', 
                    label = 'Number of public places', 
                    value = 20, 
                    min = 4, 
                    max = 100),
        sliderInput(inputId = 'pc', 
                    label = 'Probability of being infected', 
                    value = 0.1, 
                    min = 0, 
                    max = 1),
        textInput(inputId = 'gifname', 
                  label = 'File name',
                  value = 'output'),
        actionButton(inputId = 'Start',
                     label = 'Start'),
        actionButton(inputId = 'Next', 
                     label = 'Next day'),
        actionButton(inputId = 'Auto', 
                     label = 'Auto'),
        actionButton(inputId = 'Stop', 
                     label = 'Stop'),
        downloadButton("downloadgif", "Download"),
        plotOutput("Simulation"),
)

